services:

  web-front:
    ports:
      - "3000:80"

  web-api:
    ports:
      - "8080:80"
    environment:
      DB_SETTINGS__HOST: db
      DB_SETTINGS__PORT: 5432
      DB_SETTINGS__USER_NAME: ${DB_USER_NAME}
      DB_SETTINGS__PASSWORD: ${DB_USER_NAME}
      DB_SETTINGS__NAME: ${DB_NAME}
      BROKER_SETTINGS__HOST: broker
      BROKER_SETTINGS__USER_NAME: ${BROKER_USER_NAME}
      BROKER_SETTINGS__PASSWORD: ${BROKER_PASSWORD}
      FRONT_ORIGIN: http://localhost:3000
      JWT_SETTINGS__SECRET_KEY: ${JWT_SECRET_KEY}

  consumer:
    environment:
      DB_SETTINGS__HOST: db
      DB_SETTINGS__PORT: 5432
      DB_SETTINGS__USER_NAME: ${DB_USER_NAME}
      DB_SETTINGS__PASSWORD: ${DB_USER_NAME}
      DB_SETTINGS__NAME: ${DB_NAME}
      BROKER_SETTINGS__HOST: broker
      BROKER_SETTINGS__USER_NAME: ${BROKER_USER_NAME}
      BROKER_SETTINGS__PASSWORD: ${BROKER_PASSWORD}
  
  migrator:
    environment:
      CONNECTION_STRING: Host=db; User Id=${DB_USER_NAME}; Password=${DB_PASSWORD}; Database=${DB_NAME}; Port=5432
  
  db:
    ports:
      - "5432:5432"
    user: ${DB_USER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
  broker:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER_NAME}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}